### ISSUE TITLE
Undefined index 's_time'

### ISSUE THREAD

**Issue by themao** [kamisama/php-resque-ex-scheduler#3]
There is an "Undefined index 's_time'" notice in ResqueSchedule/Worker.php, and it's fixed by @michaelmessig. Could you please review and merge his code?

**Comment by jesperborgstrup** [comment]
Could you please create a tag for this new change? The latest version on Packagist is version 1.2.2 from November 29th 2013, which doesn't have this issue fixed. Thanks

**Comment by RichieB2B** [comment]
It is good to note that pull request #4 fixes this. Will there be a new release with this patch? The latest release still seems to be 1.2.2 from 2013.

**Comment by kamisama** [comment]
Just bumped 1.2.3
